spring.application.name=umbl
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
